version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./database:/usr/src/app/database
    depends_on:
      - prisma

  prisma:
    image: ghcr.io/prisma/prisma:latest
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["prisma", "migrate", "deploy"]

volumes:
  db:
