version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./src/database/dev.db:/data/dev.db