services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY
    volumes:
      - ./prisma/database:/usr/src/app/prisma/database
      - ./prisma/schema.prisma:/usr/src/app/prisma/schema.prisma
      - ./public/img:/usr/src/app/public/img
      - ./.env:/usr/src/app/.env
