services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./prisma/database:/usr/src/app/prisma/database
      - ./prisma/schema.prisma:/usr/src/app/prisma/schema.prisma

volumes:
  db: